[package]
name = "chip8"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
eframe = { version = "0.32.0", features = ["default"] }
rand = "0.9.2"
rfd = "0.15.4"
serde = { version = "1.0.219", features = ["derive"]  }
serde-big-array = "0.5.1"
